version: "3"
 
services:
  # APACHE/PHP Container
  apache-wordpress:
    image: apache-wordpress:latest
    build: docker/apache-wordpress
    depends_on:
      - db
    ports: 
      - "8080:80"   
    volumes:
      - .:/var/www/
  
  # Database Container
  db:
    image: mysql:5
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chasInsurance
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    
    volumes:
      - ./data/mysql:/var/lib/mysql



  

  
    
